# This is a basic workflow to help you get started with Actions

name: CI
permissions:
  id-token: write

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/setup-go@v5
      - run: go install github.com/openpubkey/opkssh@main

      - run: opkssh login github

      - run: ssh-keyscan shea.shyim.de >> ~/.ssh/known_hosts

      - run: ssh github@shea.shyim.de whoami
